# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# The different environments (virtual-machines or docker instances) we use
##########################################################################
executors:
  pull_request_executor:
    docker:
      - image: docker.pkg.github.com/abrahamvarricatt/personal_terraform_infra/circle_base_image:1.0

jobs:

  initial_test_job:
    executor: pull_request_executor
    steps:
      - checkout
      - run:
          name: echo to console
          command: echo "hello world"

workflows:
  version: 2

  pull_request_workflow:
    jobs:
      - initial_test_job
