# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# The different environments (virtual-machines or docker instances) we use
##########################################################################
executors:
  pull_request_executor:
    docker:
      - image: docker.pkg.github.com/abrahamvarricatt/personal_terraform_infra/circle_base_image:1.0
        auth:
          username: abrahamvarricatt
          password: $GITHUB_REPO_TOKEN

jobs:

  check-code-quality:
    executor: pull_request_executor
    steps:
      - checkout
      - run:
          name: Run pre-commit hooks
          command: git diff --no-commit-id --name-only -r origin/master | xargs pre-commit run --files

workflows:
  version: 2

  pull_request_workflow:
    jobs:
      - check-code-quality
